"""Staging and spawning a session.

The staging work is entirely freeskate's -- this module writes a scratch map
profile, has loader.staging stage it and hand back the argv freeskate would have
used, then launches that argv itself with a few loader-owned flags appended.
That keeps freeskate's build_command() the single source of truth for the
demo-path flags, and matches what play_monitored.sh / play_fixed.sh already do.
"""

from __future__ import annotations

import os
import shutil
import signal
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

from . import art, config, proc, staging
from .catalog import MapEntry, Pack


class LaunchError(Exception):
    pass


# --------------------------------------------------------------------------
# The scratch map profile
# --------------------------------------------------------------------------


def _toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "") + "'"


def write_profile(pack: Pack, entry: MapEntry) -> Path:
    """Generate freeskate/maps/_loader/map.toml for one map of one pack."""
    lines = [
        "# Generated by skate3loader on every launch - safe to delete.",
        f"# Target: {pack.name} / {entry.name} ({entry.world_id})",
        "",
        "[map]",
        f"name = {_toml_value(pack.name + ' - ' + entry.name)}",
        f"description = {_toml_value('Staged by skate3loader.')}",
        # The macro is passed on the command line instead, so the profile does
        # not pin one.
        "macro = 'none'",
        "",
        # Stock DLC stays off for CUSTOM packs: a custom package alongside the
        # shipped Danny Way / Maloof content overloads the boot content scan and
        # crashes it. A "stock" pack is the opposite case - the official content
        # IS the map, so it goes on and nothing custom is staged beside it.
        "[dlc]",
        f"enabled = {'true' if pack.kind == 'stock' else 'false'}",
    ]

    if pack.kind == "stock-game":
        # The game as it ships: nothing staged beside it at all. Not even the
        # official DLC, which is what `stock` means and which drags the boot
        # content scan back in.
        lines += [""]
    elif pack.kind == "stock":
        # Already installed under the real user root; freeskate mirrors that
        # subtree into the staged tree. Nothing to drop in or hand-place.
        lines += [""]
    elif pack.kind == "stfs":
        # A signed container installs itself: dropped into the dlc/ folder, the
        # engine's own DLC scan registers it and writes a correct header. That
        # avoids the whole hand-made-header problem raw .big packs have.
        lines += [
            "auto_install = true",
            f"dropin = [{_toml_value(pack.big)}]",
            "",
        ]
    else:
        lines += [
            "",
            "[[dlc_packages]]",
            f"source = {_toml_value(pack.big)}",
            f"package = {_toml_value(pack.package)}",
            f"name = {_toml_value(pack.name)}",
            f"header = {_toml_value(pack.header)}",
            "",
        ]

    lines += [
        "# After detecting new content the game relaunches itself asking for the",
        "# retail executable name; alias it so the relaunch resolves.",
        "[[game_files]]",
        f"source = {_toml_value(str(config.game_data_root() / 'default.xex'))}",
        "target = 'sk83_na_f.xex'",
        "",
        "[launch]",
        "# Signed in so the Locations menu is navigable.",
        "signed_in = true",
    ]
    if pack.settings:
        lines += ["", "[settings]"]
        lines += [f"{key} = {_toml_value(value)}" for key, value in sorted(pack.settings.items())]

    config.LOADER_PROFILE_DIR.mkdir(parents=True, exist_ok=True)
    manifest = config.LOADER_PROFILE_DIR / "map.toml"
    manifest.write_text("\n".join(lines) + "\n")
    return manifest


# --------------------------------------------------------------------------
# Pre-launch hygiene
# --------------------------------------------------------------------------


def game_running() -> bool:
    """Whether a LIVE game process exists.

    Zombies do not count. A defunct child still matches a process scan, and
    treating it as running is fatal here: `kill_running_game` then SIGKILLs a
    corpse for its whole timeout and raises, which is what wedged the launcher
    on an in-game map switch - the game had exited, its process just had not
    been reaped yet.
    """
    return proc.game_running()


def kill_running_game(timeout: float = 10.0) -> None:
    """Stop any running game and release its shared memory.

    Two hard-won reasons this is not optional: freeskate's own single-instance
    guard refuses to stage while a game is running, and on Linux a killed game
    leaks a 4.5 GiB /dev/shm segment that fills the tmpfs and makes the NEXT
    startup hang forever.
    """
    if not proc.kill_game(timeout=timeout):
        raise LaunchError(
            "a previous Skate 3 process would not exit; kill it manually "
            "and try again"
        )
    proc.clear_leaked_memory()


# --------------------------------------------------------------------------
# Staging
# --------------------------------------------------------------------------


# 800 ms (2026-08-23), down from 2500. The old comment here said "do not trim
# it", and it was right at the time: the settle is how long the macro waits for
# gameplay to start taking input, the game accepts it at different moments on
# different maps, and a press that lands early is simply lost.
#
# What changed is that the opening press is no longer a guess. The engine's
# `skate3_demo_path_confirm_pause` re-presses `start` until the frontend stack
# actually reads 56 (pause root), so an early press self-corrects instead of
# ruining the run. Verified by screenshot at 800 ms: Maloof 3/3 against its
# reference, GTA Rot identical to its 2500 ms landing.
#
# Raise it with SKATE3LOADER_SETTLE_MS on a slow machine.
DEFAULT_SETTLE_MS = int(os.environ.get("SKATE3LOADER_SETTLE_MS", 800))


def stage(macro: str, settle_ms: int = DEFAULT_SETTLE_MS, delay_ms: int = 260,
          windowed: bool = False, binary: Path | None = None) -> list[str]:
    """Stage the scratch profile and return the argv freeskate would have run.

    freeskate is vendored and called in-process (see loader/staging.py), so this
    is `build_command()` itself rather than a parse of what it printed.
    """
    try:
        return staging.stage(macro, settle_ms, delay_ms, windowed=windowed, binary=binary)
    except staging.StagingError as exc:
        raise LaunchError(f"staging failed: {exc}") from exc


# --------------------------------------------------------------------------
# Launching
# --------------------------------------------------------------------------


@dataclass
class Session:
    process: subprocess.Popen
    argv: list[str]
    log_file: Path
    target_world: str

    def wait(self) -> int:
        return self.process.wait()

    def stop(self) -> None:
        if self.process.poll() is None:
            try:
                self.process.terminate()
                self.process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                # kill() only signals; without the wait() the child stays a
                # ZOMBIE, which `pgrep` still reports and `kill_running_game`
                # then refuses to proceed past.
                self.process.kill()
                try:
                    self.process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    pass
            except OSError:
                # ProcessLookupError on POSIX, a plain OSError on Windows.
                pass


def _apply_overrides(argv: list[str], overrides: dict[str, str | None]) -> list[str]:
    """Append flags, replacing any freeskate already set rather than duplicating.

    A value of None REMOVES the flag instead of setting it. That is not the same
    as setting it to the empty string: `--skate3_warp_world=` makes the cvar
    parser take the NEXT argv entry as the value, so disabling the warp that way
    produced `requested world '--skate3_warp_substitute_item=false'` and left it
    very much enabled.
    """
    out = []
    for part in argv:
        name = part.split("=", 1)[0]
        if part.startswith("--") and name in {f"--{k}" for k in overrides}:
            continue
        out.append(part)
    out.extend(f"--{key}={value}" for key, value in overrides.items()
               if value is not None)
    return out


def advanced_cvars() -> dict[str, str]:
    """Engine cvars implied by the Advanced panel's saved selection."""
    from . import settings, strategies

    saved = settings.load()
    return strategies.cvars_for(saved.get("boot_strategy", "macro"),
                                saved.get("diagnostics", []))


def advanced_timings() -> dict[str, str]:
    """Menu timings the Advanced panel overrode, as environment variables.

    navigate.py reads these from the environment at import time, so they are
    applied by putting them in OUR environment before the macro is built - not
    the game's, which has no idea the macro exists.
    """
    from . import settings

    return {name: str(value) for name, value in
            settings.load().get("timings", {}).items()}


def child_env() -> dict[str, str]:
    """The environment the GAME gets, scrubbed of everything the loader needs.

    Frozen, the loader runs inside a PyInstaller bundle whose runtime hooks point
    LD_LIBRARY_PATH, GI_TYPELIB_PATH, GDK_PIXBUF_MODULE_FILE, GIO_MODULE_DIR,
    GTK_PATH and XDG_DATA_DIRS at its own private GTK stack. Handing that to the
    engine makes it load OUR libstdc++ and OUR GTK, and the resulting undefined
    symbol looks exactly like an engine regression. PyInstaller stashes the
    original of each variable it overwrites in <NAME>_ORIG for precisely this.
    """
    env = dict(os.environ)
    for name in ("LD_LIBRARY_PATH", "DYLD_LIBRARY_PATH", "DYLD_FRAMEWORK_PATH"):
        original = env.pop(f"{name}_ORIG", None)
        if original:
            env[name] = original
        else:
            env.pop(name, None)
    for name in (
        "GI_TYPELIB_PATH", "GDK_PIXBUF_MODULE_FILE", "GDK_PIXBUF_MODULEDIR",
        "GIO_MODULE_DIR", "GTK_PATH", "GTK_DATA_PREFIX", "GTK_EXE_PREFIX",
        "GSETTINGS_SCHEMA_DIR", "XDG_DATA_DIRS", "PANGO_LIBDIR",
        "PANGO_SYSCONFDIR", "FONTCONFIG_PATH", "FONTCONFIG_FILE",
    ):
        env.pop(name, None)
    if config.IS_LINUX:
        # X11 rather than Wayland, so the loading screen's keep-above binds.
        env["GDK_BACKEND"] = "x11"
    else:
        env.pop("GDK_BACKEND", None)
    return env


def launch(
    pack: Pack,
    entry: MapEntry,
    macro: str,
    all_packs: list[Pack] | None = None,
    binary: Path | None = None,
    windowed: bool = False,
    settle_ms: int = DEFAULT_SETTLE_MS,
    delay_ms: int = 260,
    open_picker: bool = False,
    manual: bool = False,
    extra_cvars: dict[str, str] | None = None,
) -> Session:
    """Stage the pack, then spawn the game aimed at one map.

    `manual` stages the DLC and then gets out of the way: no macro, no warp, no
    loading cover. You navigate the game's own menus yourself.

    It exists as a diagnostic. Every hypothesis killed so far about the maps
    that never load was tested with this automation still driving, so "the
    loader breaks these maps" and "these maps are broken" have never been told
    apart. Manual mode is the control: if a pack reaches its world by hand, the
    fault is here; if it does not, it is not.
    """
    binary = Path(binary) if binary else config.default_binary()
    # Whatever the Advanced panel last saved. Experiments live there rather than
    # in this call's arguments so that the GUI, the CLI and a sweep all get the
    # same launch.
    extra_cvars = {**advanced_cvars(), **(extra_cvars or {})}
    if not binary.is_file():
        raise LaunchError(f"game binary not found at {binary}")

    kill_running_game()
    write_profile(pack, entry)

    # Start from a clean log so the watcher never reads a previous session's
    # milestones. freeskate rotates it during staging, so this must come after.
    argv = stage(macro, settle_ms=settle_ms, delay_ms=delay_ms,
                 windowed=windowed, binary=binary)
    argv[0] = str(binary)

    overrides = {
        # Without this the tail sees nothing until the buffer flushes.
        "log_flush_interval": "1",
        # The in-game loading cover. Drawing it inside the game's own window is
        # what makes menu automation invisible: an external window cannot be
        # kept above a fullscreen game reliably (impossible on Wayland, and on
        # X11 the fullscreen layer outranks always-on-top).
        "skate3_loader_overlay": "true",
        "skate3_loader_overlay_title": entry.name,
        "skate3_loader_overlay_subtitle": pack.name,
        "skate3_loader_overlay_hue": f"{art.hue_for(entry.world_id):.4f}",
        **_level_picker_cvars(pack, all_packs, include_broken=manual),
        "skate3_loader_open_picker": "true" if open_picker else "false",
        # -1 leaves the boot path alone; otherwise the engine walks the menu to
        # this map using cursor feedback, which is far quicker than a fixed
        # 40-press macro and stops exactly at the end of the list.
        # Engine-side boot navigation stays off: the pad macro above is the
        # path that is actually verified to land on the right map.
        "skate3_loader_boot_index": "-1",
        # Repoint every map row at the world we actually want. The identity a
        # Locations row carries is a pair of HASHES in the item (+0x18/+0x1C)
        # plus a per-world object at +0x00; copying them from the wanted map's
        # item onto every row makes ANY row load it. Measured at ~60 ms, once.
        #
        # This does NOT replace the navigation above, it backstops it: with both
        # active, a macro that lands on the wrong row still loads the right map,
        # and a pack whose sub-list order we guessed wrong stops mattering.
        "skate3_warp_world": entry.world_id,
        "skate3_warp_substitute_item": "true",
        # Skip loading the stock world entirely. These two redirect the BOOT
        # stream to the requested map, so University is never loaded - the boot
        # streams the map we actually want. On their own they leave the session
        # pointing at the stock world and the renderer with nothing to draw
        # (a black screen); the menu confirm above then fixes the session, with
        # the map's data already resident.
        #
        # Measured: 27.1 / 27.3 / 27.2 s to playable against 30.7 / 32.5 s with
        # the stock world loaded first, and MORE consistent, because the
        # variable-cost University load is gone. The black stretch is invisible
        # behind the in-engine loading overlay.
        "skate3_warp_substitute_folder": "true",
        "skate3_warp_substitute_slug": "true",
        # The frontend's 4-second boot hold. Between language select and the EA
        # logo it runs a timer that accumulates the frame delta and only lets
        # boot continue at 4000 ms; the guest main thread is asleep for all of
        # it (measured: zero new guest calls for 4.18 s, Main XThread under 5%
        # of a core). Completing it on the first tick is 4.1 s off every boot,
        # and it is engine-gated to the pre-press-start window.
        "skate3_boot_skip_fe_hold": "true",
        # Deferred overlapped completions sleep before running and again before
        # the XN_SYS_UI notification, serialised on one kernel dispatch thread.
        # A boot performs exactly one, so this is only ~0.25 s - but it is free.
        "kernel_overlapped_delay_ms": "0",
        # Emits `fe-debug: stack ...` on every screen change - the menu-state
        # feedback channel the loader uses to tell navigation from streaming.
        # The middle Xbox button opens the level picker. SDL drops the Guide
        # button unless this is on, so the picker_chord default ("guide")
        # would silently never fire without it.
        "guide_button": "true",
        "skate3_fe_debug": "true",
        "skate3_hang_watchdog_seconds": "15",
        # A pack whose maps are SPOTS inside one world cannot use the row
        # patch. PatchItemEntries finds its template by the wanted world's pack
        # record, so when 18 entries all report world_id "San Vanelona" it
        # repoints every row at whichever spot matched first and all 18 load
        # the same place. Those packs navigate by row instead - see
        # Pack.spots_share_world and navigate.build_macro's `row_patch`.
        **({"skate3_warp_substitute_item": "false"} if pack.spots_share_world else {}),
        # Leave the warp completely alone for a pack whose world ids match no
        # spawn node - see Pack.warp_safe. Handing it a world it cannot resolve
        # makes it substitute a spawn node that does not exist, the world's
        # geometry never arrives, and on screen you get the skybox and fall
        # through it. Empty disables the whole warp, so the game reaches the map
        # by ordinary menu navigation instead - slower, because the stock world
        # loads first, but correct.
        #
        # This must come AFTER the enabling defaults above; a dict literal takes
        # the last value for a key.
        **({} if pack.warp_safe else {
            # None removes the flag; empty would be read as "value is the next
            # argv entry" and re-enable the warp with a garbage world name.
            "skate3_warp_world": None,
            "skate3_warp_substitute_folder": "false",
            "skate3_warp_substitute_slug": "false",
            "skate3_warp_substitute_item": "false",
            "skate3_warp_substitute_node": "false",
            "skate3_warp_substitute_lookup": "false",
        }),
        # Per-pack overrides beat the defaults above. The map.toml [settings]
        # block cannot do it on its own - everything here is appended to the
        # argv afterwards and would win. Danny Way is the case that needs it:
        # its stream folder is DLC_DW_MegaCompund, so the warp's DIST_ + world
        # redirects the boot stream at a directory that does not exist and the
        # world data never arrives (measured 0/3 with the warp on, 3/3 with it
        # off, while every other DLC world is 3/3 WITH it).
        **{str(k): str(v) for k, v in (pack.settings or {}).items()},
        # MANUAL MODE: stage the DLC and then get out of the way entirely.
        #
        # Ordered after the per-pack settings deliberately - this is a control
        # condition, and a pack-specific workaround leaking into it would be
        # exactly the confound the mode exists to remove.
        #
        # `skate3_warp_world` must be REMOVED (None), not blanked: the cvar
        # parser takes the next argv entry as the value, so `--skate3_warp_world=`
        # silently swallows the following flag as its world name.
        #
        # All FIVE warp switches have to go off. `_node` and `_lookup` default
        # to TRUE and are not in the usual disable list, which is why an earlier
        # per-pack workaround that turned off only folder/slug/item never
        # actually stopped the substitution.
        #
        # And the overlay MUST be off. It hides itself when the macro completes,
        # and in manual mode there is no macro - leaving it on covers the menus
        # forever, which reads as "manual mode is broken too".
        **({
            "skate3_loader_overlay": "false",
            "skate3_warp_world": None,
            "skate3_warp_substitute_item": "false",
            "skate3_warp_substitute_folder": "false",
            "skate3_warp_substitute_slug": "false",
            "skate3_warp_substitute_node": "false",
            "skate3_warp_substitute_lookup": "false",
            # Keep the frontend chatter: it is the diagnostic.
            "skate3_fe_debug": "true",
        } if manual else {}),
        # Investigation flags (--skate3_trace and friends) go last so a caller
        # can override anything above.
        **(extra_cvars or {}),
    }
    argv = _apply_overrides(argv, overrides)
    if windowed and "--fullscreen=false" not in argv:
        argv.append("--fullscreen=false")

    log_file = _log_path(argv)
    if log_file.exists():
        log_file.unlink()

    env = child_env()

    process = subprocess.Popen(argv, cwd=config.RUNTIME, env=env)
    _install_signal_forwarding(process)
    return Session(
        process=process, argv=argv, log_file=log_file, target_world=entry.world_id
    )


def _level_picker_cvars(pack: Pack, all_packs: list[Pack] | None,
                        include_broken: bool = False) -> dict[str, str]:
    """Everything the in-game picker needs to list maps across every pack.

    Maps in the staged pack switch in place; maps in any other pack are marked
    and, when chosen, written to the request file for the launcher to act on --
    the installed DLC set is fixed at boot, so those need a relaunch.

    Maps recorded as `stalls` are LEFT OUT. Picking one costs a relaunch and a
    200-second wait to arrive back where you started, which is not a choice
    worth offering - and the picker is a controller-driven list where a label
    is easy to miss. If it cannot load, it is not on the menu.

    `include_broken` puts them back, for manual mode: there the broken ones are
    the entire point, and the person picking is deliberately trying to reach
    one by hand.
    """
    packs = all_packs if all_packs is not None else [pack]
    names: list[str] = []
    owners: list[str] = []
    indices: list[str] = []
    worlds: list[str] = []
    for candidate in packs:
        for entry in sorted(candidate.maps, key=lambda m: m.sub_index):
            if entry.status == "stalls" and not include_broken:
                continue
            names.append(entry.name)
            owners.append(candidate.id)
            indices.append(str(entry.sub_index))
            # The world id is what the engine repoints the menu rows at, so an
            # in-session switch can target a map without relying on its row.
            worlds.append(entry.world_id)
    if config.REQUEST_FILE.exists():
        config.REQUEST_FILE.unlink()
    return {
        "skate3_loader_levels": "|".join(names),
        "skate3_loader_level_packs": "|".join(owners),
        "skate3_loader_level_indices": "|".join(indices),
        "skate3_loader_level_worlds": "|".join(worlds),
        "skate3_loader_current_pack": pack.id,
        "skate3_loader_request_path": str(config.REQUEST_FILE),
    }


def read_request() -> tuple[str, int] | None:
    """A pending relaunch request from the in-game picker: (pack id, map index)."""
    try:
        lines = config.REQUEST_FILE.read_text().splitlines()
    except OSError:
        return None
    if len(lines) < 2:
        return None
    try:
        return lines[0].strip(), int(lines[1].strip())
    except ValueError:
        return None


def clear_request() -> None:
    try:
        config.REQUEST_FILE.unlink()
    except OSError:
        pass


def _log_path(argv: list[str]) -> Path:
    for part in argv:
        if part.startswith("--log_file="):
            return Path(part.split("=", 1)[1])
    return config.LOG_FILE


def _install_signal_forwarding(process: subprocess.Popen) -> None:
    """Never leave the game orphaned holding its shm segment."""

    def forward(_signum, _frame):
        try:
            process.terminate()
        except OSError:
            pass

    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            signal.signal(sig, forward)
        except ValueError:
            # Not on the main thread; the GUI installs its own handling.
            pass


def clear_profile() -> None:
    """Remove the scratch profile (used on exit; purely cosmetic)."""
    if config.LOADER_PROFILE_DIR.is_dir():
        shutil.rmtree(config.LOADER_PROFILE_DIR, ignore_errors=True)
