"""Staging and spawning a session.

The staging work is entirely freeskate's -- this module writes a scratch map
profile, asks `freeskate play _loader --dry-run` to stage it and print the argv
it would have used, then launches that argv itself with a few loader-owned flags
appended. That keeps freeskate's build_command() the single source of truth for
the demo-path flags, and matches what play_monitored.sh / play_fixed.sh already do.
"""

from __future__ import annotations

import os
import re
import shutil
import signal
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

from . import art, config
from .catalog import MapEntry, Pack

ANSI = re.compile(r"\x1b\[[0-9;]*m")


class LaunchError(Exception):
    pass


# --------------------------------------------------------------------------
# The scratch map profile
# --------------------------------------------------------------------------


def _toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "") + "'"


def write_profile(pack: Pack, entry: MapEntry) -> Path:
    """Generate freeskate/maps/_loader/map.toml for one map of one pack."""
    lines = [
        "# Generated by skate3loader on every launch - safe to delete.",
        f"# Target: {pack.name} / {entry.name} ({entry.world_id})",
        "",
        "[map]",
        f"name = {_toml_value(pack.name + ' - ' + entry.name)}",
        f"description = {_toml_value('Staged by skate3loader.')}",
        # The macro is passed on the command line instead, so the profile does
        # not pin one.
        "macro = 'none'",
        "",
        # Stock DLC stays off for CUSTOM packs: a custom package alongside the
        # shipped Danny Way / Maloof content overloads the boot content scan and
        # crashes it. A "stock" pack is the opposite case - the official content
        # IS the map, so it goes on and nothing custom is staged beside it.
        "[dlc]",
        f"enabled = {'true' if pack.kind == 'stock' else 'false'}",
    ]

    if pack.kind == "stock":
        # Already installed under the real user root; freeskate mirrors that
        # subtree into the staged tree. Nothing to drop in or hand-place.
        lines += [""]
    elif pack.kind == "stfs":
        # A signed container installs itself: dropped into the dlc/ folder, the
        # engine's own DLC scan registers it and writes a correct header. That
        # avoids the whole hand-made-header problem raw .big packs have.
        lines += [
            "auto_install = true",
            f"dropin = [{_toml_value(pack.big)}]",
            "",
        ]
    else:
        lines += [
            "",
            "[[dlc_packages]]",
            f"source = {_toml_value(pack.big)}",
            f"package = {_toml_value(pack.package)}",
            f"name = {_toml_value(pack.name)}",
            f"header = {_toml_value(pack.header)}",
            "",
        ]

    lines += [
        "# After detecting new content the game relaunches itself asking for the",
        "# retail executable name; alias it so the relaunch resolves.",
        "[[game_files]]",
        f"source = {_toml_value(str(config.INSTALL / 'game' / 'default.xex'))}",
        "target = 'sk83_na_f.xex'",
        "",
        "[launch]",
        "# Signed in so the Locations menu is navigable.",
        "signed_in = true",
    ]
    if pack.settings:
        lines += ["", "[settings]"]
        lines += [f"{key} = {_toml_value(value)}" for key, value in sorted(pack.settings.items())]

    config.LOADER_PROFILE_DIR.mkdir(parents=True, exist_ok=True)
    manifest = config.LOADER_PROFILE_DIR / "map.toml"
    manifest.write_text("\n".join(lines) + "\n")
    return manifest


# --------------------------------------------------------------------------
# Pre-launch hygiene
# --------------------------------------------------------------------------


def game_running() -> bool:
    """Whether a LIVE game process exists.

    Zombies do not count. A defunct child still matches `pgrep -x skate3`, and
    treating it as running is fatal here: `kill_running_game` then SIGKILLs a
    corpse for its whole timeout and raises, which is what wedged the launcher
    on an in-game map switch - the game had exited, its process just had not
    been reaped yet.
    """
    found = subprocess.run(["pgrep", "-x", "skate3"], capture_output=True, text=True)
    if found.returncode != 0:
        return False
    for line in found.stdout.split():
        try:
            with open(f"/proc/{line}/stat", "r") as handle:
                state = handle.read().split(") ", 1)[1].split()[0]
        except (OSError, IndexError):
            continue
        if state != "Z":
            return True
    return False


def kill_running_game(timeout: float = 10.0) -> None:
    """Stop any running game and release its shared memory.

    Two hard-won reasons this is not optional: freeskate's own single-instance
    guard refuses to stage while a game is running, and a killed game leaks a
    4.5 GiB /dev/shm segment that fills the tmpfs and makes the NEXT startup hang
    forever.
    """
    deadline = time.monotonic() + timeout
    while game_running() and time.monotonic() < deadline:
        # SIGKILL every time round: a game mid-teardown can ignore gentler
        # signals, and freeskate refuses to stage while ANY copy is alive, so a
        # half-dead process turns the next relaunch into a hard failure.
        subprocess.run(["pkill", "-9", "-x", "skate3"], capture_output=True)
        time.sleep(0.25)
    if game_running():
        raise LaunchError(
            "a previous Skate 3 process would not exit; kill it manually "
            "(pkill -9 -x skate3) and try again"
        )
    for leaked in Path("/dev/shm").glob("xenia_memory_*"):
        try:
            leaked.unlink()
        except OSError:
            pass


# --------------------------------------------------------------------------
# Staging
# --------------------------------------------------------------------------


# 2500 ms, and do not trim it. The short settles (700 -> 400) were justified by
# the loader reporting LANDED, which is inferred from STREAM lines and is true
# whatever the menu does - see the note in navigate.py. Verified by screenshot:
# at 2500 ms, requesting Spillway puts you in Spillway, twice running.
DEFAULT_SETTLE_MS = 2500


def stage(macro: str, settle_ms: int = DEFAULT_SETTLE_MS, delay_ms: int = 260) -> list[str]:
    """Stage the scratch profile and return the argv freeskate would have run.

    `--dry-run` is not a no-op: it performs the entire stage and only stops short
    of spawning, printing each argv part indented under "launching:".
    """
    if not config.FREESKATE_BIN.is_file():
        raise LaunchError(f"freeskate not found at {config.FREESKATE_BIN}")

    cmd = [
        str(config.FREESKATE_BIN),
        "play",
        config.LOADER_PROFILE,
        "--dry-run",
        "--macro",
        macro,
        "--settle",
        str(settle_ms),
        "--delay",
        str(delay_ms),
    ]
    result = subprocess.run(
        cmd, cwd=config.FREESKATE_DIR, capture_output=True, text=True, timeout=600
    )
    stdout = ANSI.sub("", result.stdout)
    if result.returncode != 0:
        stderr = ANSI.sub("", result.stderr).strip()
        raise LaunchError(f"staging failed ({result.returncode}): {stderr or stdout.strip()}")

    argv = _parse_argv(stdout)
    if not argv:
        raise LaunchError(f"could not parse the launch command from freeskate output:\n{stdout}")
    return argv


def _parse_argv(stdout: str) -> list[str]:
    argv: list[str] = []
    collecting = False
    for line in stdout.splitlines():
        if line.strip().endswith("launching:"):
            collecting = True
            continue
        if collecting:
            if line.startswith("    ") and line.strip():
                argv.append(line.strip())
            elif argv:
                break
    return argv


# --------------------------------------------------------------------------
# Launching
# --------------------------------------------------------------------------


@dataclass
class Session:
    process: subprocess.Popen
    argv: list[str]
    log_file: Path
    target_world: str

    def wait(self) -> int:
        return self.process.wait()

    def stop(self) -> None:
        if self.process.poll() is None:
            try:
                self.process.terminate()
                self.process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                # kill() only signals; without the wait() the child stays a
                # ZOMBIE, which `pgrep` still reports and `kill_running_game`
                # then refuses to proceed past.
                self.process.kill()
                try:
                    self.process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    pass
            except ProcessLookupError:
                pass


def _apply_overrides(argv: list[str], overrides: dict[str, str | None]) -> list[str]:
    """Append flags, replacing any freeskate already set rather than duplicating.

    A value of None REMOVES the flag instead of setting it. That is not the same
    as setting it to the empty string: `--skate3_warp_world=` makes the cvar
    parser take the NEXT argv entry as the value, so disabling the warp that way
    produced `requested world '--skate3_warp_substitute_item=false'` and left it
    very much enabled.
    """
    out = []
    for part in argv:
        name = part.split("=", 1)[0]
        if part.startswith("--") and name in {f"--{k}" for k in overrides}:
            continue
        out.append(part)
    out.extend(f"--{key}={value}" for key, value in overrides.items()
               if value is not None)
    return out


def launch(
    pack: Pack,
    entry: MapEntry,
    macro: str,
    all_packs: list[Pack] | None = None,
    binary: Path | None = None,
    windowed: bool = False,
    settle_ms: int = DEFAULT_SETTLE_MS,
    delay_ms: int = 260,
    open_picker: bool = False,
    extra_cvars: dict[str, str] | None = None,
) -> Session:
    """Stage the pack, then spawn the game aimed at one map."""
    binary = Path(binary) if binary else config.default_binary()
    if not binary.is_file():
        raise LaunchError(f"game binary not found at {binary}")

    kill_running_game()
    write_profile(pack, entry)

    # Start from a clean log so the watcher never reads a previous session's
    # milestones. freeskate rotates it during staging, so this must come after.
    argv = stage(macro, settle_ms=settle_ms, delay_ms=delay_ms)
    argv[0] = str(binary)

    overrides = {
        # Without this the tail sees nothing until the buffer flushes.
        "log_flush_interval": "1",
        # The in-game loading cover. Drawing it inside the game's own window is
        # what makes menu automation invisible: an external window cannot be
        # kept above a fullscreen game reliably (impossible on Wayland, and on
        # X11 the fullscreen layer outranks always-on-top).
        "skate3_loader_overlay": "true",
        "skate3_loader_overlay_title": entry.name,
        "skate3_loader_overlay_subtitle": pack.name,
        "skate3_loader_overlay_hue": f"{art.hue_for(entry.world_id):.4f}",
        **_level_picker_cvars(pack, all_packs),
        "skate3_loader_open_picker": "true" if open_picker else "false",
        # -1 leaves the boot path alone; otherwise the engine walks the menu to
        # this map using cursor feedback, which is far quicker than a fixed
        # 40-press macro and stops exactly at the end of the list.
        # Engine-side boot navigation stays off: the pad macro above is the
        # path that is actually verified to land on the right map.
        "skate3_loader_boot_index": "-1",
        # Repoint every map row at the world we actually want. The identity a
        # Locations row carries is a pair of HASHES in the item (+0x18/+0x1C)
        # plus a per-world object at +0x00; copying them from the wanted map's
        # item onto every row makes ANY row load it. Measured at ~60 ms, once.
        #
        # This does NOT replace the navigation above, it backstops it: with both
        # active, a macro that lands on the wrong row still loads the right map,
        # and a pack whose sub-list order we guessed wrong stops mattering.
        "skate3_warp_world": entry.world_id,
        "skate3_warp_substitute_item": "true",
        # Skip loading the stock world entirely. These two redirect the BOOT
        # stream to the requested map, so University is never loaded - the boot
        # streams the map we actually want. On their own they leave the session
        # pointing at the stock world and the renderer with nothing to draw
        # (a black screen); the menu confirm above then fixes the session, with
        # the map's data already resident.
        #
        # Measured: 27.1 / 27.3 / 27.2 s to playable against 30.7 / 32.5 s with
        # the stock world loaded first, and MORE consistent, because the
        # variable-cost University load is gone. The black stretch is invisible
        # behind the in-engine loading overlay.
        "skate3_warp_substitute_folder": "true",
        "skate3_warp_substitute_slug": "true",
        # The frontend's 4-second boot hold. Between language select and the EA
        # logo it runs a timer that accumulates the frame delta and only lets
        # boot continue at 4000 ms; the guest main thread is asleep for all of
        # it (measured: zero new guest calls for 4.18 s, Main XThread under 5%
        # of a core). Completing it on the first tick is 4.1 s off every boot,
        # and it is engine-gated to the pre-press-start window.
        "skate3_boot_skip_fe_hold": "true",
        # Deferred overlapped completions sleep before running and again before
        # the XN_SYS_UI notification, serialised on one kernel dispatch thread.
        # A boot performs exactly one, so this is only ~0.25 s - but it is free.
        "kernel_overlapped_delay_ms": "0",
        # Emits `fe-debug: stack ...` on every screen change - the menu-state
        # feedback channel the loader uses to tell navigation from streaming.
        # The middle Xbox button opens the level picker. SDL drops the Guide
        # button unless this is on, so the picker_chord default ("guide")
        # would silently never fire without it.
        "guide_button": "true",
        "skate3_fe_debug": "true",
        "skate3_hang_watchdog_seconds": "15",
        # A pack whose maps are SPOTS inside one world cannot use the row
        # patch. PatchItemEntries finds its template by the wanted world's pack
        # record, so when 18 entries all report world_id "San Vanelona" it
        # repoints every row at whichever spot matched first and all 18 load
        # the same place. Those packs navigate by row instead - see
        # Pack.spots_share_world and navigate.build_macro's `row_patch`.
        **({"skate3_warp_substitute_item": "false"} if pack.spots_share_world else {}),
        # Leave the warp completely alone for a pack whose world ids match no
        # spawn node - see Pack.warp_safe. Handing it a world it cannot resolve
        # makes it substitute a spawn node that does not exist, the world's
        # geometry never arrives, and on screen you get the skybox and fall
        # through it. Empty disables the whole warp, so the game reaches the map
        # by ordinary menu navigation instead - slower, because the stock world
        # loads first, but correct.
        #
        # This must come AFTER the enabling defaults above; a dict literal takes
        # the last value for a key.
        **({} if pack.warp_safe else {
            # None removes the flag; empty would be read as "value is the next
            # argv entry" and re-enable the warp with a garbage world name.
            "skate3_warp_world": None,
            "skate3_warp_substitute_folder": "false",
            "skate3_warp_substitute_slug": "false",
            "skate3_warp_substitute_item": "false",
            "skate3_warp_substitute_node": "false",
            "skate3_warp_substitute_lookup": "false",
        }),
        # Per-pack overrides beat the defaults above. The map.toml [settings]
        # block cannot do it on its own - everything here is appended to the
        # argv afterwards and would win. Danny Way is the case that needs it:
        # its stream folder is DLC_DW_MegaCompund, so the warp's DIST_ + world
        # redirects the boot stream at a directory that does not exist and the
        # world data never arrives (measured 0/3 with the warp on, 3/3 with it
        # off, while every other DLC world is 3/3 WITH it).
        **{str(k): str(v) for k, v in (pack.settings or {}).items()},
        # Investigation flags (--skate3_trace and friends) go last so a caller
        # can override anything above.
        **(extra_cvars or {}),
    }
    argv = _apply_overrides(argv, overrides)
    if windowed and "--fullscreen=false" not in argv:
        argv.append("--fullscreen=false")

    log_file = _log_path(argv)
    if log_file.exists():
        log_file.unlink()

    env = dict(os.environ)
    # X11 rather than Wayland, so the loading screen's keep-above actually binds.
    env["GDK_BACKEND"] = "x11"

    process = subprocess.Popen(argv, cwd=config.RUNTIME, env=env)
    _install_signal_forwarding(process)
    return Session(
        process=process, argv=argv, log_file=log_file, target_world=entry.world_id
    )


def _level_picker_cvars(pack: Pack, all_packs: list[Pack] | None) -> dict[str, str]:
    """Everything the in-game picker needs to list maps across every pack.

    Maps in the staged pack switch in place; maps in any other pack are marked
    and, when chosen, written to the request file for the launcher to act on --
    the installed DLC set is fixed at boot, so those need a relaunch.
    """
    packs = all_packs if all_packs is not None else [pack]
    names: list[str] = []
    owners: list[str] = []
    indices: list[str] = []
    worlds: list[str] = []
    for candidate in packs:
        for entry in sorted(candidate.maps, key=lambda m: m.sub_index):
            names.append(entry.name)
            owners.append(candidate.id)
            indices.append(str(entry.sub_index))
            # The world id is what the engine repoints the menu rows at, so an
            # in-session switch can target a map without relying on its row.
            worlds.append(entry.world_id)
    if config.REQUEST_FILE.exists():
        config.REQUEST_FILE.unlink()
    return {
        "skate3_loader_levels": "|".join(names),
        "skate3_loader_level_packs": "|".join(owners),
        "skate3_loader_level_indices": "|".join(indices),
        "skate3_loader_level_worlds": "|".join(worlds),
        "skate3_loader_current_pack": pack.id,
        "skate3_loader_request_path": str(config.REQUEST_FILE),
    }


def read_request() -> tuple[str, int] | None:
    """A pending relaunch request from the in-game picker: (pack id, map index)."""
    try:
        lines = config.REQUEST_FILE.read_text().splitlines()
    except OSError:
        return None
    if len(lines) < 2:
        return None
    try:
        return lines[0].strip(), int(lines[1].strip())
    except ValueError:
        return None


def clear_request() -> None:
    try:
        config.REQUEST_FILE.unlink()
    except OSError:
        pass


def _log_path(argv: list[str]) -> Path:
    for part in argv:
        if part.startswith("--log_file="):
            return Path(part.split("=", 1)[1])
    return config.LOG_FILE


def _install_signal_forwarding(process: subprocess.Popen) -> None:
    """Never leave the game orphaned holding its shm segment."""

    def forward(_signum, _frame):
        try:
            process.terminate()
        except ProcessLookupError:
            pass

    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            signal.signal(sig, forward)
        except ValueError:
            # Not on the main thread; the GUI installs its own handling.
            pass


def clear_profile() -> None:
    """Remove the scratch profile (used on exit; purely cosmetic)."""
    if config.LOADER_PROFILE_DIR.is_dir():
        shutil.rmtree(config.LOADER_PROFILE_DIR, ignore_errors=True)
